---
# Define as variáveis de caminho para o localhost
repo_dir: "{{ lookup('env', 'HOME') }}/HIAAC-FL-Testbed-SBRC/ansible"
testbed_dir: "{{ lookup('env', 'HOME') }}/TESTBED"
vault_pass_file: "{{ testbed_dir }}/.ansible_vault_pass"
server_pid_file: "{{ testbed_dir }}/server.pid"
uv_bin: "{{ user_home_dir_output.stdout }}/.local/bin/uv"