---
- hosts:
  - Raspberry_Pi
  - Jetsons
  become: no
  tasks:
    - name: Obter o diretório de trabalho remoto
      ansible.builtin.command: pwd
      register: remote_dir_output

    - name: Obter o diretório de trabalho local (onde o Ansible está rodando)
      local_action: command pwd
      register: local_dir_output
      changed_when: false # Este comando não altera nada, então não marque como "changed"

    - name: Copy Hello World
      ansible.builtin.copy:
        src: "{{ local_dir_output.stdout }}/hello.py"
        dest: "{{ remote_dir_output.stdout }}/hello.py"
        # remote_src: yes

    - name: Execute Hello World
      command:
        chdir: "{{ remote_dir_output.stdout }}"
        cmd: "python3 hello.py"
      register: file_output
  
    - name: show output
      ansible.builtin.debug:
        msg: "Command output: {{ file_output.stdout }}"
        # remote_src: yes

    # - name: Mostrar o diretório local
    #   ansible.builtin.debug:
    #     msg: "Diretório Local (na máquina de controle) é: {{ local_dir_output.stdout }}"


# ---
# - hosts:
#     - Raspberry_Pi
#     - Jetsons
#   become: yes
# #  vars_files:
# #    - "{{ lookup('env', 'HOME') }}/HIAAC-FL-Testbed/ansible/vault.yml"

#   tasks:

#     # --- ETAPA 1: Lógica para descobrir dinamicamente o usuário, home e GRUPO ---
#     - name: Descobrir o home directory real do usuário de conexão
#       shell: "getent passwd {{ ansible_user }} | cut -d: -f6"
#       register: user_home_dir_output
#       changed_when: false
#       become: no

#     - name: Descobrir o grupo primário real do usuário de conexão
#       shell: "id -gn {{ ansible_user }}" 
#       register: user_group_output
#       changed_when: false
#       become: no

#     - name: Definir variáveis de fato com os caminhos e grupos corretos
#       set_fact:
#         correct_user_home: "{{ user_home_dir_output.stdout }}"
#         correct_user_group: "{{ user_group_output.stdout }}"

# # --- ETAPA 2: --- #

#     - name: Garantir que o diretório do cliente exista no Pi
#       file:
#         path: "{{ correct_user_home }}/FilesTestbed/flower_client"
#         state: directory
#         owner: "{{ ansible_user }}"
#         group: "{{ correct_user_group }}" 
#         mode: '0755'

#     - name: Copiar o arquivo client.py para os Pis
#       copy:
#         # Origem no server
#         src: "{{ lookup('env', 'HOME') }}/TESTBED/client.py"
#         dest: "{{ correct_user_home }}/FilesTestbed/flower_client/client.py"
#         owner: "{{ ansible_user }}"
#         group: "{{ correct_user_group }}" 
#         mode: '0755'